import type {NextPage} from 'next';
import Head from 'next/head';
import {FormEvent, useEffect, useState} from 'react';
import {ContentCarousel} from '../components/content-carousel';

const announcements = [
   {tag: 'Dashboard focus', title: 'CTF standings + learning hub', body: 'This prototype centres on one place to discover competitions, track team momentum, and find the next skill to practise.', date: 'Prototype'},
   {tag: 'Workshop', title: 'Intro to Web Security', body: 'A hands-on starter session built around safe practice labs and beginner-friendly CTF concepts.', date: 'Fall term'},
];
const projects = [
   {icon: '!', title: 'LLM Prompt Injection Firewall', body: 'A concept for screening adversarial prompts before they reach an LLM.', featured: true},
   {icon: '</>', title: 'Writeup library', body: 'A searchable home for team solve notes, tooling tips, and post-CTF lessons.'},
   {icon: '#', title: 'Team finder', body: 'A lightweight way for students to share interests and form balanced competition teams.'},
];
const resources = [
   {title: 'Web Security', text: 'Build web-security fundamentals through guided, legal practice.', links: [{label: 'PortSwigger Web Security Academy', note: 'Free, hands-on labs covering nearly every web vuln class; the gold standard starting point.', href: 'https://portswigger.net/web-security'}, {label: 'OWASP Top 10', note: 'The standard reference for the most critical web app risks.', href: 'https://owasp.org/www-project-top-ten/'}, {label: 'Google XSS Game', note: 'Short, fun challenges specifically on cross-site scripting.', href: 'https://xss-game.appspot.com/'}, {label: 'HackTricks', note: 'A massive practical wiki on exploitation techniques, great as a reference once you are past basics.', href: 'https://book.hacktricks.xyz/'}]},
   {title: 'CTF Starter Kit', text: 'Start with approachable challenges, then find a competition to join.', links: [{label: 'CTFtime.org', note: 'The CTF calendar and global rankings; also where your standings data could come from.', href: 'https://ctftime.org/'}, {label: 'picoCTF', note: 'Free and beginner-friendly; the classic first CTF for students.', href: 'https://picoctf.org/'}, {label: 'OverTheWire Wargames', note: 'Linux and binary challenge ladders for building fundamentals.', href: 'https://overthewire.org/wargames/'}, {label: 'CTF Field Guide', note: 'Trail of Bits explains CTF categories and how to approach each one.', href: 'https://trailofbits.github.io/ctf/'}]},
   {title: 'Career Toolkit', text: 'Turn practice into a portfolio and learn what security roles involve.', links: [{label: 'TryHackMe', note: 'Guided learning paths, including free material, that bridge CTF skills into job-relevant knowledge.', href: 'https://tryhackme.com/'}, {label: 'LeetCode', note: 'For the software-engineering side of interviews, not just security.', href: 'https://leetcode.com/'}, {label: 'OSCP / Security Certification Roadmap', note: 'A useful reference for students considering pentesting careers.', href: 'https://www.offsec.com/courses/pen-200/'}], tip: 'Write up your CTF solves; even short ones. Recruiters and interviewers love seeing documented problem-solving.'},
];
const ctfEvents = [
   {title: 'Upcoming-event feed', date: 'Synced from CTFtime', detail: 'Filter upcoming events by format, time commitment, and team interest.'},
   {title: 'Team sign-up board', date: 'Student-managed', detail: 'Match students by interests such as web, crypto, pwn, forensics, and OSINT.'},
];
const socialLinks = [
   {name: 'Discord', href: 'https://discord.com/invite/nfjz2WmWrJ', symbol: 'D'},
   {name: 'Instagram', href: 'https://instagram.com/mcmastercss', symbol: 'O'},
   {name: 'Linktree', href: 'https://linktr.ee/mcmastercss', symbol: '+'},
   {name: 'Email', href: 'mailto:cybersociety@mcmaster.ca', symbol: 'mail'},
];

const Home: NextPage = () => {
   const [menuOpen, setMenuOpen] = useState(false);
   const [submitted, setSubmitted] = useState(false);
   const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true); };
   useEffect(() => {
      let previousScroll = window.scrollY;
      const header = document.querySelector('.site-header');
      const contactIntro = document.querySelector('.contact-grid > div');
      const socialContainer = document.createElement('div');
      socialContainer.className = 'social-links';
      socialContainer.setAttribute('aria-label', 'Follow McMaster CyberSociety');
      socialLinks.forEach((social) => {
         const link = document.createElement('a'); link.href = social.href; link.setAttribute('aria-label', social.name); link.title = social.name;
         if (social.name !== 'Email') { link.target = '_blank'; link.rel = 'noreferrer'; }
         link.innerHTML = `<span aria-hidden="true">${social.symbol}</span><span>${social.name}</span>`; socialContainer.appendChild(link);
      });
      contactIntro?.appendChild(socialContainer);
      const handleScroll = () => { const currentScroll = window.scrollY; header?.classList.toggle('header-hidden', currentScroll > 88 && currentScroll > previousScroll); previousScroll = currentScroll; };
      window.addEventListener('scroll', handleScroll, {passive: true});
      return () => { window.removeEventListener('scroll', handleScroll); socialContainer.remove(); };
   }, []);
   return <><Head><title>McMaster CyberSociety | CTF & Learning Dashboard</title><meta name="description" content="A CTF standings and cybersecurity learning-resources dashboard for McMaster CyberSociety." /><link rel="icon" href="/McMaster-Cybersociety-Logo.jpg" /></Head>
      <header className="site-header"><a className="brand" href="#home" aria-label="McMaster CyberSociety home"><img src="/McMaster-Cybersociety-Logo.jpg" alt="McMaster CyberSociety logo" /><span><strong>McMaster</strong><small>CyberSociety</small></span></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Toggle navigation">Menu</button><nav className={menuOpen ? 'open' : ''} aria-label="Main navigation"><a href="#ctf">CTF dashboard</a><a href="#resources">Learning resources</a><a href="#projects">Roadmap</a><a href="#about">About</a><a className="nav-cta" href="#contact">Get involved <span>-&gt;</span></a></nav></header>
      <main id="home"><section className="hero section-shell"><div className="hero-copy"><p className="eyebrow">McMaster University &middot; Hamilton, ON</p><h1>Learn, compete,<br /><em>level up together.</em></h1><p className="hero-text">A CTF standings and learning-resources dashboard for McMaster students exploring cybersecurity.</p><p className="focus-note"><strong>Project focus:</strong> I built the broader site to show the vision; the CTF dashboard and resource hub are the pieces I want to develop for CyberSociety.</p><div className="hero-actions"><a className="button button-primary" href="#ctf">Explore the dashboard <span>-&gt;</span></a><a className="button button-plain" href="#resources">Start learning <span>-&gt;</span></a></div></div><aside className="next-event"><p className="card-label"><span className="status-dot" /> Dashboard concept</p><div className="event-date"><b>01</b><span>ONE<br />HUB</span></div><h2>Find a CTF.<br />Find your team.</h2><p>Competitions, standings, and skills in one student-first space.</p><a href="#ctf">See the data plan <span>-&gt;</span></a></aside></section>
      <section id="updates" className="section-shell content-section"><div className="section-heading"><p className="eyebrow">01 / The pitch</p><h2>Built around the idea.</h2><p>The supporting pages give the dashboard a home; the competition and learning tools are the core of this prototype.</p></div><ContentCarousel items={announcements} pageSize={2} className="announcement-grid" label="announcements" renderItem={(item) => <article className="announcement-card" key={item.title}><div><span className="tag">{item.tag}</span><span className="date">{item.date}</span></div><h3>{item.title}</h3><p>{item.body}</p><a href="#ctf">Explore the concept <span>-&gt;</span></a></article>} /></section>
      <section id="ctf" className="section-shell content-section ctf-section"><div className="section-heading"><p className="eyebrow">02 / Capture the flag dashboard</p><h2>CTF central</h2><p>Track team momentum, discover the next competition, and make it easy to find collaborators.</p></div><div className="ctf-grid"><article className="ranking-card"><p className="card-label">Sample standings</p><ol><li><span>1</span><b>byte_bandits</b><em>4,920 pts</em></li><li><span>2</span><b>root_access</b><em>3,840 pts</em></li><li><span>3</span><b>mcmaster_cyber</b><em>3,275 pts</em></li></ol><p className="data-note"><strong>Data plan:</strong> replace these sample rows with CTFtime event and team data, then add a small server-side sync to normalize scores and refresh standings.</p><a href="https://ctftime.org/api/" target="_blank" rel="noreferrer">View CTFtime API <span>-&gt;</span></a></article><article className="upcoming-card"><p className="card-label"><span className="status-dot" /> Proposed workflow</p><ContentCarousel items={ctfEvents} pageSize={1} className="event-carousel" label="dashboard workflow" renderItem={(event) => <div key={event.title}><h3>{event.title}</h3><p>{event.date}</p><div className="team-callout"><span>+</span><div><b>How it becomes real</b><p>{event.detail}</p></div></div><a className="button button-primary" href="https://ctftime.org/api/" target="_blank" rel="noreferrer">CTFtime API docs <span>-&gt;</span></a></div>} /></article></div></section>
      <section id="resources" className="resource-band"><div className="section-shell"><div className="section-heading"><p className="eyebrow">03 / Learning hub</p><h2>Resources for the curious</h2><p>Curated starting points for safe, legal practice and career exploration.</p></div><ContentCarousel items={resources} pageSize={3} className="resource-grid" label="resources" renderItem={(resource, i) => <article className="resource-card" key={resource.title}><span>0{i + 1}</span><h3>{resource.title}</h3><p>{resource.text}</p><ul>{resource.links.map((link) => <li key={link.href}><a href={link.href} target="_blank" rel="noreferrer"><strong>{link.label} <i>-&gt;</i></strong><small>{link.note}</small></a></li>)}</ul>{resource.tip && <aside className="portfolio-tip"><b>Portfolio tip</b><p>{resource.tip}</p></aside>}</article>} /></div></section>
      <section id="projects" className="section-shell content-section projects-section"><div className="section-heading"><p className="eyebrow">04 / What comes next</p><h2>Roadmap</h2><p>Small tools that make learning, collaborating, and sharing progress easier for the community.</p></div><ContentCarousel items={projects} pageSize={3} className="project-grid" label="roadmap projects" renderItem={(project, i) => <article className="project-card" key={project.title}><div className={`project-art art-${i + 1} ${project.featured ? 'firewall-art' : ''}`}>{project.featured ? <div className="firewall-preview" aria-label="Prompt firewall preview"><p><span>INPUT</span> Ignore prior instructions</p><div><b>SCAN</b><i>Threat detected</i></div><p><span>VERDICT</span> <strong>BLOCKED</strong></p></div> : <><span>{project.icon}</span><small>CYBERSOCIETY<br />ROADMAP</small></>}</div><div className="project-content"><p className="card-label">{project.featured ? 'Cybersecurity project' : 'Dashboard extension'}</p><h3>{project.title}</h3><p>{project.body}</p></div></article>} /></section>
      <section id="about" className="section-shell content-section about-section"><div className="about-copy"><p className="eyebrow">05 / About CyberSociety</p><h2>Built for the question-askers.</h2><p>McMaster CyberSociety is imagined as a student-led space to practise security skills responsibly, share what we learn, and compete together.</p><a className="button button-dark" href="#contact">Get in touch <span>-&gt;</span></a></div><div className="values-card"><p className="card-label">What guides the dashboard</p><div><span>01</span><h3>Curiosity first</h3><p>Make the first step into cybersecurity feel approachable.</p></div><div><span>02</span><h3>Learn together</h3><p>Connect individual practice to a team and community.</p></div><div><span>03</span><h3>Make progress visible</h3><p>Celebrate participation, learning, and competition momentum.</p></div></div></section>
      <section id="contact" className="contact-section"><div className="section-shell contact-grid"><div><p className="eyebrow">06 / Let&apos;s talk</p><h2>Bring your<br /><em>next challenge.</em></h2><p>Have a CTF idea, resource to add, or feedback on the dashboard? I&apos;d love to hear it.</p><a href="mailto:cybersociety@mcmaster.ca">cybersociety@mcmaster.ca <span>-&gt;</span></a></div><form onSubmit={submit}><label>Your name<input required placeholder="Jane Doe" /></label><label>Email address<input required type="email" placeholder="you@mcmaster.ca" /></label><label>What can we help with?<select defaultValue=""><option value="" disabled>Choose a topic</option><option>CTF dashboard</option><option>Learning resources</option><option>Team finding</option><option>Something else</option></select></label><label>Message<textarea required placeholder="Tell us a little more..." rows={4} /></label><button className="button button-primary" type="submit">{submitted ? 'Message received!' : 'Send message'} <span>-&gt;</span></button></form></div></section></main>
      <footer><div className="section-shell footer-inner"><a className="brand" href="#home"><img src="/McMaster-Cybersociety-Logo.jpg" alt="McMaster CyberSociety logo" /><span><strong>McMaster</strong><small>CyberSociety</small></span></a><p>CTF standings and learning-resources dashboard concept.</p><a href="#home">Back to top &uarr;</a></div></footer></>;
};
export default Home;
