import type {NextPage} from 'next';
import Head from 'next/head';
import {FormEvent, useState} from 'react';

const announcements = [
   {tag: 'Featured', title: 'Fall Kickoff Social', body: 'Meet the community, learn about our plans, and find your next CTF teammate.', date: 'Sep 30 · 6:30 PM'},
   {tag: 'Workshop', title: 'Intro to Web Security', body: 'A hands-on starter session. Bring a laptop and your curiosity.', date: 'Oct 8 · 5:30 PM'},
];
const projects = [
   {icon: '⌘', title: 'Project title', body: 'A short, editable description for a student or club project.'},
   {icon: '◈', title: 'Project title', body: 'Add a screenshot, stack, team credits, and a link when ready.'},
   {icon: '⌁', title: 'Project title', body: 'A space to show work the community is proud of.'},
];
const resources = [
   {title: 'Web Security', text: 'A practical path through browser security, common flaws, and secure coding.'},
   {title: 'CTF Starter Kit', text: 'Recommended tools, beginner-friendly challenges, and learning paths.'},
   {title: 'Career Toolkit', text: 'Templates, event notes, and advice for building a cybersecurity portfolio.'},
];

const Home: NextPage = () => {
   const [menuOpen, setMenuOpen] = useState(false);
   const [submitted, setSubmitted] = useState(false);
   const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true); };
   return <><Head><title>McMaster Computer Science Society</title><meta name="description" content="A demo dashboard for the McMaster Computer Science Society." /><link rel="icon" href="/McMaster-Cybersociety-Logo.jpg" /></Head>
      <header className="site-header"><a className="brand" href="#home" aria-label="McMaster Computer Science Society home"><img src="/McMaster-Cybersociety-Logo.jpg" alt="McMaster Computer Science Society logo" /><span><strong>McMaster</strong><small>Computer Science Society</small></span></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Toggle navigation">☰</button><nav className={menuOpen ? 'open' : ''} aria-label="Main navigation"><a href="#updates">Updates</a><a href="#projects">Projects</a><a href="#ctf">CTFs</a><a href="#resources">Resources</a><a href="#about">About</a><a className="nav-cta" href="#contact">Get involved <span>↗</span></a></nav></header>
      <main id="home"><section className="hero section-shell"><div className="hero-copy"><p className="eyebrow">McMaster University · Hamilton, ON</p><h1>Learn, build,<br /><em>and break things</em>.</h1><p className="hero-text">A home for curious McMaster students to explore computer science, cybersecurity, and the people behind both.</p><div className="hero-actions"><a className="button button-primary" href="#contact">Join the community <span>→</span></a><a className="button button-plain" href="#updates">See what&apos;s on <span>↓</span></a></div></div><aside className="next-event"><p className="card-label"><span className="status-dot" /> Next up</p><div className="event-date"><b>30</b><span>SEP<br />TUE</span></div><h2>Fall Kickoff<br />Social</h2><p>6:30 PM · TBA</p><a href="#contact">Save your spot <span>→</span></a></aside></section>
      <section id="updates" className="section-shell content-section"><div className="section-heading"><p className="eyebrow">01 / Stay in the loop</p><h2>Announcements</h2><p>Swap these demo cards with your latest society news.</p></div><div className="announcement-grid">{announcements.map((item) => <article className="announcement-card" key={item.title}><div><span className="tag">{item.tag}</span><span className="date">{item.date}</span></div><h3>{item.title}</h3><p>{item.body}</p><a href="#contact">Read update <span>→</span></a></article>)}</div></section>
      <section id="projects" className="section-shell content-section projects-section"><div className="section-heading"><p className="eyebrow">02 / Made at Mac</p><h2>Project showcase</h2><p>A simple gallery template for student and club work.</p></div><div className="project-grid">{projects.map((project, i) => <article className="project-card" key={project.icon}><div className={`project-art art-${i + 1}`}><span>{project.icon}</span><small>YOUR PROJECT<br />IMAGE / PREVIEW</small></div><div className="project-content"><p className="card-label">Featured project</p><h3>{project.title}</h3><p>{project.body}</p><a href="#contact">View project <span>↗</span></a></div></article>)}</div></section>
      <section id="ctf" className="section-shell content-section ctf-section"><div className="section-heading"><p className="eyebrow">03 / Capture the flag</p><h2>CTF central</h2><p>Keep score, find your next competition, and build your team.</p></div><div className="ctf-grid"><article className="ranking-card"><p className="card-label">Recent rankings</p><ol><li><span>1</span><b>byte_bandits</b><em>4,920 pts</em></li><li><span>2</span><b>root_access</b><em>3,840 pts</em></li><li><span>3</span><b>mcmaster_cs</b><em>3,275 pts</em></li></ol><a href="#contact">See full rankings <span>→</span></a></article><article className="upcoming-card"><p className="card-label"><span className="status-dot" /> Coming up</p><h3>MapleCTF 2026</h3><p>Oct 18–20 · Online</p><div className="team-callout"><span>◎</span><div><b>Looking for a team?</b><p>Tell us what you&apos;re into and we&apos;ll help you find one.</p></div></div><a className="button button-primary" href="#contact">Register interest <span>→</span></a></article></div></section>
      <section id="resources" className="resource-band"><div className="section-shell"><div className="section-heading"><p className="eyebrow">04 / Keep learning</p><h2>Resources for the curious</h2></div><div className="resource-grid">{resources.map((resource, i) => <a className="resource-card" href="#contact" key={resource.title}><span>0{i + 1}</span><h3>{resource.title}</h3><p>{resource.text}</p><b>Explore <i>→</i></b></a>)}</div></div></section>
      <section id="about" className="section-shell content-section about-section"><div className="about-copy"><p className="eyebrow">05 / About the society</p><h2>Built for the question-askers.</h2><p>We&apos;re a student-led community making room to explore technical ideas, share what we learn, and have a great time doing it.</p><a className="button button-dark" href="#contact">Meet the team <span>→</span></a></div><div className="values-card"><p className="card-label">What guides us</p><div><span>01</span><h3>Curiosity first</h3><p>There&apos;s no such thing as a silly question here.</p></div><div><span>02</span><h3>Learn together</h3><p>Knowledge grows when it&apos;s shared.</p></div><div><span>03</span><h3>Make it real</h3><p>Turn an idea into something you can show.</p></div></div></section>
      <section id="contact" className="contact-section"><div className="section-shell contact-grid"><div><p className="eyebrow">06 / Let&apos;s talk</p><h2>Bring us your<br /><em>bright idea.</em></h2><p>Use this form as a starter for project submissions, event questions, or a general hello.</p><a href="mailto:hello@mcmastercs.ca">hello@mcmastercs.ca <span>↗</span></a></div><form onSubmit={submit}><label>Your name<input required placeholder="Jane Doe" /></label><label>Email address<input required type="email" placeholder="you@mcmaster.ca" /></label><label>What can we help with?<select defaultValue=""><option value="" disabled>Choose a topic</option><option>Project submission</option><option>Joining the society</option><option>Event question</option><option>Something else</option></select></label><label>Message<textarea required placeholder="Tell us a little more..." rows={4} /></label><button className="button button-primary" type="submit">{submitted ? 'Message received!' : 'Send message'} <span>→</span></button></form></div></section></main>
      <footer><div className="section-shell footer-inner"><a className="brand" href="#home"><img src="/McMaster-Cybersociety-Logo.jpg" alt="" /><span><strong>McMaster</strong><small>Computer Science Society</small></span></a><p>Demo dashboard template · Replace this content with your own.</p><a href="#home">Back to top ↑</a></div></footer></>;
};
export default Home;
